In [13]:
from hashhop.generate import MultiHopEval

In [18]:
datapoint = MultiHopEval.make_one(
    n_chars_problem=100,
    num_queries=2,
    hops=2,
    hash_pair_str_length=8,
    chain_of_thought=True,
)

3


In [19]:
len(datapoint.prompt)

125

In [20]:
print(datapoint.prompt)

AFrxkqfj = JIYvEYdA
SSfeWGnE = tsdebCzv
KwDmeNsN = ZrcNaDka
tsdebCzv = 'LjdsqCXN'
JIYvEYdA = 'ADWMHciL'
ZrcNaDka = 'qoTVBdeq'


In [21]:
print(datapoint.completion)

COMPLETION:
Hops=2

CoT=True

KwDmeNsN = 'ZrcNaDka = qoTVBdeq'
SSfeWGnE = 'tsdebCzv = LjdsqCXN'



In [6]:
print(datapoint.targets)

{'Feibrmpt': 'RJPYIrAN = kAhIcqEO', 'HTVRobJh': 'bukcjkRh = vGrHamRa', 'rvRdAUjy': 'EBlouJPM = HUpdUunC'}


In [1]:
import torch

In [6]:
torch.randint(low=0, high=128, size=(3, 2, 10))

tensor([[[  9,  12, 113, 111,  29,  91,   4,   0,  29, 103],
         [ 47,  47,  14,  22,  41,  14,  94, 112,  47,  30]],

        [[ 58,  17,  81,  57,  91,  58,  31,  56,   0,  86],
         [ 67, 106,  41, 127,  71, 118,  65,  53,  19,  62]],

        [[ 84, 112,  18,  98,  27,  73, 100,  31,   0,  62],
         [ 66, 116,  59,  52,  46,  14,  13,  84, 103,  40]]])

In [ ]:
def _make_levels(n_chains: int, hops: int, string_length: int) -> List[Dict[str, str]]:
    levels = [
        {
            make_random_string(length=string_length): make_random_string(length=string_length)
            for _ in range(n_chains)
        }
    ]
    for _ in range(hops - 1):
        levels.append(
            {v: make_random_string(length=string_length) for v in levels[-1].values()}
        )
    return levels

In [1]:
import torch

In [2]:
hashes = torch.randint(low=0, high=128, size=(10, 3))
hashes[:-1, :]

tensor([[100,  51,  21],
        [ 98,  83,  44],
        [ 57, 107,  23],
        [110,  48,  49],
        [ 54,  43,  60],
        [ 72,   3,  33],
        [117, 122,  74],
        [ 23,  11, 113],
        [ 29,  75,  82]])

In [3]:
hashes[1:, :]

tensor([[ 98,  83,  44],
        [ 57, 107,  23],
        [110,  48,  49],
        [ 54,  43,  60],
        [ 72,   3,  33],
        [117, 122,  74],
        [ 23,  11, 113],
        [ 29,  75,  82],
        [ 18,  58,  88]])

In [4]:
A = torch.cat([hashes[:-1, :], torch.zeros(9, 1, dtype=torch.long), hashes[1:, :], torch.ones(9, 1, dtype=torch.long)], dim=1)
A

tensor([[100,  51,  21,   0,  98,  83,  44,   1],
        [ 98,  83,  44,   0,  57, 107,  23,   1],
        [ 57, 107,  23,   0, 110,  48,  49,   1],
        [110,  48,  49,   0,  54,  43,  60,   1],
        [ 54,  43,  60,   0,  72,   3,  33,   1],
        [ 72,   3,  33,   0, 117, 122,  74,   1],
        [117, 122,  74,   0,  23,  11, 113,   1],
        [ 23,  11, 113,   0,  29,  75,  82,   1],
        [ 29,  75,  82,   0,  18,  58,  88,   1]])

In [6]:
A.flatten()

tensor([100,  51,  21,   0,  98,  83,  44,   1,  98,  83,  44,   0,  57, 107,
         23,   1,  57, 107,  23,   0, 110,  48,  49,   1, 110,  48,  49,   0,
         54,  43,  60,   1,  54,  43,  60,   0,  72,   3,  33,   1,  72,   3,
         33,   0, 117, 122,  74,   1, 117, 122,  74,   0,  23,  11, 113,   1,
         23,  11, 113,   0,  29,  75,  82,   1,  29,  75,  82,   0,  18,  58,
         88,   1])

In [1]:
import string
import torch

from hashhop.hashhop import HashHop, hh_to_string

In [2]:
hh = HashHop(max_tokens=100, hash_len=8, n_hops=2, cot=True)

In [4]:
A, B = hh.sample(4)

original hashes:
LUJUTKUV=HTsMEsSl
HTsMEsSl=nvPhOAUJ
dVzodGPi=SjFznhZg
SjFznhZg=WDOVXyWe

shuffling
LUJUTKUV=HTsMEsSl
SjFznhZg=WDOVXyWe
dVzodGPi=SjFznhZg
HTsMEsSl=nvPhOAUJ

chain to find:
LUJUTKUV=HTsMEsSl=nvPhOAUJ


In [13]:
len(tensor_to_string(hh.sample(2)[0]))

100

In [10]:
hashes = torch.randint(low=0, high=10, size=(10, 3), )
hashes

tensor([[9, 6, 9],
        [3, 7, 1],
        [9, 4, 5],
        [7, 3, 2],
        [0, 3, 6],
        [0, 6, 7],
        [3, 5, 1],
        [4, 1, 5],
        [0, 8, 7],
        [2, 0, 6]])