In [4]:
from hashhop.generate import MultiHopEval

In [5]:
datapoint = MultiHopEval.make_one(
    n_chars_problem=100,
    num_queries=2,
    hops=2,
    hash_pair_str_length=8,
    chain_of_thought=True,
)

3


In [6]:
len(datapoint.prompt)

125

In [7]:
print(datapoint.prompt)

AANeqmRt = 'OluYZuQK'
ACaSKIzJ = 'VYEIkmIN'
HGnXYZpJ = ajRhlHyD
mkhIDgHV = ACaSKIzJ
ajRhlHyD = 'XIwlnQDq'
EByCJiOx = AANeqmRt


In [8]:
print(datapoint.completion)

COMPLETION:
Hops=2

CoT=True

mkhIDgHV = 'ACaSKIzJ = VYEIkmIN'
EByCJiOx = 'AANeqmRt = OluYZuQK'



In [9]:
print(datapoint.targets)

{'mkhIDgHV': 'ACaSKIzJ = VYEIkmIN', 'EByCJiOx': 'AANeqmRt = OluYZuQK', 'HGnXYZpJ': 'ajRhlHyD = XIwlnQDq'}


In [10]:
import torch

In [11]:
torch.randint(low=0, high=128, size=(3, 2, 10))

tensor([[[ 76,  95, 118,  56,  58,  36,  99,   3,  74,  83],
         [115,  55,  11, 103,  20,  35,  46, 116,  86, 121]],

        [[ 90,  14,  49, 117, 119,  34, 114,  43, 109,  21],
         [ 59,  18,  24,  64,  50, 102,  33,  61,  95,  73]],

        [[  9,  11, 119,  74,  77,  87,  14,  76,  63,  99],
         [ 73,  35,  76,  14, 111,  80, 124,  49,  38, 114]]])

In [12]:
def _make_levels(n_chains: int, hops: int, string_length: int) -> List[Dict[str, str]]:
    levels = [
        {
            make_random_string(length=string_length): make_random_string(length=string_length)
            for _ in range(n_chains)
        }
    ]
    for _ in range(hops - 1):
        levels.append(
            {v: make_random_string(length=string_length) for v in levels[-1].values()}
        )
    return levels

NameError: name 'List' is not defined

In [ ]:
import torch

In [ ]:
hashes = torch.randint(low=0, high=128, size=(10, 3))
hashes[:-1, :]

tensor([[100,  51,  21],
        [ 98,  83,  44],
        [ 57, 107,  23],
        [110,  48,  49],
        [ 54,  43,  60],
        [ 72,   3,  33],
        [117, 122,  74],
        [ 23,  11, 113],
        [ 29,  75,  82]])

In [ ]:
hashes[1:, :]

tensor([[ 98,  83,  44],
        [ 57, 107,  23],
        [110,  48,  49],
        [ 54,  43,  60],
        [ 72,   3,  33],
        [117, 122,  74],
        [ 23,  11, 113],
        [ 29,  75,  82],
        [ 18,  58,  88]])

In [ ]:
A = torch.cat([hashes[:-1, :], torch.zeros(9, 1, dtype=torch.long), hashes[1:, :], torch.ones(9, 1, dtype=torch.long)], dim=1)
A

tensor([[100,  51,  21,   0,  98,  83,  44,   1],
        [ 98,  83,  44,   0,  57, 107,  23,   1],
        [ 57, 107,  23,   0, 110,  48,  49,   1],
        [110,  48,  49,   0,  54,  43,  60,   1],
        [ 54,  43,  60,   0,  72,   3,  33,   1],
        [ 72,   3,  33,   0, 117, 122,  74,   1],
        [117, 122,  74,   0,  23,  11, 113,   1],
        [ 23,  11, 113,   0,  29,  75,  82,   1],
        [ 29,  75,  82,   0,  18,  58,  88,   1]])

In [ ]:
A.flatten()

tensor([100,  51,  21,   0,  98,  83,  44,   1,  98,  83,  44,   0,  57, 107,
         23,   1,  57, 107,  23,   0, 110,  48,  49,   1, 110,  48,  49,   0,
         54,  43,  60,   1,  54,  43,  60,   0,  72,   3,  33,   1,  72,   3,
         33,   0, 117, 122,  74,   1, 117, 122,  74,   0,  23,  11, 113,   1,
         23,  11, 113,   0,  29,  75,  82,   1,  29,  75,  82,   0,  18,  58,
         88,   1])

In [7]:
import string
import torch

from hashhop.hashhop import HashHopSampler, hh_to_string

In [28]:
hh = HashHopSampler(max_tokens=3_000, hash_len=8, max_hops=4, cot=False)

In [29]:
A, B = hh.sample(512, verbose=False)

In [32]:
A.shape[1]+B.shape[1]

2969

In [33]:
A.shape

torch.Size([512, 2952])

In [34]:
B.shape

torch.Size([512, 17])

In [36]:
torch.cat([A, B], dim=1).shape

torch.Size([512, 2969])

In [ ]:
N = torch.tensor([3, 5, 2, 7, 4])
result = torch.zeros((5, 10), dtype=torch.int32)
column_indices = torch.arange(10).unsqueeze(0).expand(5, 10)
mask = column_indices < N.unsqueeze(1)
result[mask] = 1

In [ ]:
result

tensor([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
len(A[0])

NameError: name 'A' is not defined

In [ ]:
A = torch.randint(low=0, high=10, size=(5, 10))
N = torch.randint(low=2, high=5, size=(5,))

A, N

(tensor([[8, 2, 0, 8, 7, 6, 3, 6, 8, 6],
         [5, 3, 2, 0, 0, 7, 6, 2, 0, 9],
         [0, 8, 3, 9, 5, 7, 4, 2, 7, 3],
         [2, 6, 9, 0, 7, 1, 3, 9, 7, 5],
         [8, 0, 6, 1, 0, 2, 8, 2, 3, 8]]),
 tensor([4, 2, 4, 4, 3]))

In [ ]:
range_tensor = torch.arange(10).unsqueeze(0).expand(5, -1)
mask = range_tensor >= (10 - N.unsqueeze(1))
mask

tensor([[False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True]])

In [ ]:
A

tensor([[8, 2, 0, 8, 7, 6, 3, 6, 8, 6],
        [5, 3, 2, 0, 0, 7, 6, 2, 0, 9],
        [0, 8, 3, 9, 5, 7, 4, 2, 7, 3],
        [2, 6, 9, 0, 7, 1, 3, 9, 7, 5],
        [8, 0, 6, 1, 0, 2, 8, 2, 3, 8]])

In [ ]:
B = A * mask # pas besoin de passer par B, on peut directement faire les ops sur A
B

tensor([[0, 0, 0, 0, 0, 0, 3, 6, 8, 6],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
        [0, 0, 0, 0, 0, 0, 4, 2, 7, 3],
        [0, 0, 0, 0, 0, 0, 3, 9, 7, 5],
        [0, 0, 0, 0, 0, 0, 0, 2, 3, 8]])

In [ ]:
A, N

(tensor([[8, 2, 0, 8, 7, 6, 3, 6, 8, 6],
         [5, 3, 2, 0, 0, 7, 6, 2, 0, 9],
         [0, 8, 3, 9, 5, 7, 4, 2, 7, 3],
         [2, 6, 9, 0, 7, 1, 3, 9, 7, 5],
         [8, 0, 6, 1, 0, 2, 8, 2, 3, 8]]),
 tensor([4, 2, 4, 4, 3]))

In [ ]:
# on pad
C = torch.cat([A, torch.zeros(5, 2, dtype=torch.long)], dim=1) # 5 = bs, 2 = max(N)-min(N)
C

tensor([[8, 2, 0, 8, 7, 6, 3, 6, 8, 6, 0, 0],
        [5, 3, 2, 0, 0, 7, 6, 2, 0, 9, 0, 0],
        [0, 8, 3, 9, 5, 7, 4, 2, 7, 3, 0, 0],
        [2, 6, 9, 0, 7, 1, 3, 9, 7, 5, 0, 0],
        [8, 0, 6, 1, 0, 2, 8, 2, 3, 8, 0, 0]])

In [ ]:
cols = (10-N.unsqueeze(1)) + torch.arange(4)

In [ ]:
selected_columns = C[torch.arange(C.size(0)).unsqueeze(1), cols]
selected_columns

tensor([[3, 6, 8, 6],
        [0, 9, 0, 0],
        [4, 2, 7, 3],
        [3, 9, 7, 5],
        [2, 3, 8, 0]])

In [ ]:
cols = torch.cat([(10-N.unsqueeze(1)), torch.tensor([10]).expand(5, 1)], dim=1)
selected_columns = C[torch.arange(C.size(0)).unsqueeze(1), cols]
selected_columns # ok mais à faire sur C non paddé (ie A ?)

tensor([[3, 0],
        [0, 0],
        [4, 0],
        [3, 0],
        [2, 0]])

In [ ]:
N.max() > 3

tensor(True)

In [ ]:
torch.randint(low=0, high=2, size=(10,))

tensor([0, 0, 1, 1, 1, 0, 0, 1, 0, 1])

In [ ]:
torch.zeros(N.max())

tensor([0., 0., 0., 0.])

In [ ]:
hashes = torch.randint(low=0, high=10, size=(5, 10))
N = torch.randint(low=2, high=5, size=(5,))

hashes, N

(tensor([[6, 7, 6, 9, 5, 8, 4, 4, 0, 7],
         [9, 0, 0, 5, 1, 9, 1, 0, 4, 5],
         [2, 2, 4, 0, 6, 4, 3, 0, 3, 1],
         [5, 5, 7, 7, 2, 6, 3, 0, 7, 1],
         [1, 7, 8, 4, 6, 6, 1, 0, 9, 5]]),
 tensor([2, 3, 3, 4, 2]))

In [ ]:
cols = torch.cat([(10-1-N.unsqueeze(1)), torch.tensor([10-1]).expand(5, 1)], dim=1)
selected_columns = hashes[torch.arange(hashes.size(0)).unsqueeze(1), cols]
selected_columns

tensor([[4, 7],
        [1, 5],
        [3, 1],
        [6, 1],
        [0, 5]])

In [3]:
import torch

from hashhop.generator import HashHopGenerator
from hashhop.hashhop import hh_to_string

In [4]:
ds = HashHopGenerator(max_tokens=200, batch_size=16, hash_len=8, max_hops=4, cot=True)
loader = torch.utils.data.DataLoader(ds, batch_size=None, num_workers=8, pin_memory=True, worker_init_fn=None)
iter_ = iter(loader)

In [8]:
x, y = next(iter_)

In [6]:
print(hh_to_string(x[2]))

YENmsgBN=lBhZlMia
XDvihkDw=YENmsgBN
mYsRVbOE=dGlkZSdO
vHfrywei=XDvihkDw
McIIlOve=QaEgWpMr
QaEgWpMr=mVXAStYM
dGlkZSdO=McIIlOve
lBhZlMia=sibNQYEY
QaEgWpMr=mVXAStYM__________________________


In [7]:
print(hh_to_string(y[2]))

ENmsgBN=lBhZlMia
XDvihkDw=YENmsgBN
mYsRVbOE=dGlkZSdO
vHfrywei=XDvihkDw
McIIlOve=QaEgWpMr
QaEgWpMr=mVXAStYM
dGlkZSdO=McIIlOve
lBhZlMia=sibNQYEY
QaEgWpMr=mVXAStYM___________________________
